import type { Metadata } from "next";
import "./globals.css";
import { Teko } from "next/font/google";

const teko = Teko({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-teko",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${teko.className} dark antialiased`}>{children}</body>
    </html>
  );
}
